package com.ercan.fyberchallenge.util;

import com.ercan.fyberchallenge.data.model.RequestParam;

import java.util.Collections;
import java.util.List;

/**
 * Created by Ercan on 2/10/2016.
 */
public class CommonUtils {

    /**
     * Generates a hashkey with rules given in <a href ="http://developer.fyber.com/content/current/android/offer-wall/offer-api/">Fyber Mobile Offer API Documentation </a>
     * @param params parameter string generated by {@link #stringfyRequestParams(List)}
     * @return SHA1 hash of given parameters or null if an error occurred
     */
    public static String generateHashKey(String params, String apiKey){
        String hashKey = params;
        hashKey += apiKey;//already has '&' at end

        try {
            //hash with SHA1 algorithm
            hashKey = Sha1.getHash(hashKey);

        }catch (Exception e){
            e.printStackTrace();
            hashKey = null;
        }

        return hashKey == null ? hashKey : hashKey.toLowerCase() ;//just to be sure
    }

    /**
     * Builds parameters in  name=value& pairs in alphabetical order
     * <b>WARNING</b> this method leaves a "&" cahracter at the end of string
     * @param params
     * @return
     */
    public static String stringfyRequestParams(List<RequestParam> params){
        String parameterString = "";
        Collections.sort(params);//sort alphabetically;
        for(RequestParam requestParam : params ){
            parameterString += requestParam.toString()+"&";
        }

        return  parameterString;
    }

    /**
     * Returns current Unix timestamp
     * @return unix timestamp
     */
    public static String getUnixTimeStamp() {
        return String.valueOf(System.currentTimeMillis() / 1000L);
    }
}
